version: '3'

services:
  postgres:
    image: aded/postgres-twchd:${TAG}
    volumes:
      - pg-data:/var/lib/postgresql
    deploy:
      mode: global
      placement:
        constraints: [node.hostname == archhost]
      restart_policy:
        condition: on-failure
  bot:
    image: aded/twchd:${TAG}
    volumes:
      - ${PWD}/config/example.yml:/app/config.yml
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  pg-data:
