version: '3'

services:
  db:
    image: postgres:11
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - 5432:5432
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  bot:
    image: aded/twchd:3.0
    volumes:
      - /home/ivan/go/src/twchd/config/example.yml:/app/config.yml
    environment:
      - TWITCH_ACCOUNT=${TWITCH_ACCOUNT}
      - TWITCH_OAUTH=${TWITCH_OAUTH}
      - TWCHD_PG_PASSWD=${TWCHD_PG_PASSWD}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  pg-data:
