version: '3'

services:
  db:
    image: aded/postgres-twchd:3.0-6-g7043e04
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - 5432:5432
    deploy:
      mode: global
      placement:
        constraints: [node.hostname == archhost]
      restart_policy:
        condition: on-failure

volumes:
  pg-data:
