version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
#      - 9300:9300
#    network:
#      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    ports:
      - 5601:5601

volumes:
  es-data:

#networks:
#  elastic-net:
