version: '3'

services:
  db:
    image: postgres:11
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - 5432:5432
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

volumes:
  pg-data:
