[[constraint]]
  name = "github.com/gempir/go-twitch-irc"
  version = "2.1.0"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
