## Twitch Client settings
# Account name
account_name: vanya109

# Account oauth token
# https://twitchapps.com/tmi/
account_token: oauth:kic4lme1k221w4c6soyrppnwros6b0

# List accounts for joining
join_to:
  - vanya83

## Elastic Client settings
# Name of index for creation
index: twitchchat

# Name of type for creation
# Don't forget to change mapping.json
type: message

pipeline: msg-parser
