## Twitch Client settings
# Account name
account_name: ${TWITCH_ACCOUNT}

# Account oauth token
# https://twitchapps.com/tmi/
account_token: ${TWITCH_OAUTH}

# List accounts for joining
join_to:
  - vanya83

## Elastic Client settings
# Name of index for creation
index: twitchchat

# Name of type for creation
# Don't forget to change mapping.json
type: message

# Name of pipeline for processing raw message from grabber
pipeline: msg-parser
