## Twitch Client settings
# Account name
account_name: ${TWITCH_ACCOUNT}

# Account oauth token
# https://twitchapps.com/tmi/
account_token: ${TWITCH_OAUTH}

# List accounts for listening
join_to:
  - stealth_unit
  - yesitshappy
  - allenfallen

## Postgres DB settings
address: 127.0.0.1

port: 5432

username: twchd

password: ${TWCHD_PG_PASSWD}

database: twchd
