## Twitch Client settings
# Account name
account_name: ${TWITCH_ACCOUNT}

# Account oauth token
# https://twitchapps.com/tmi/
account_token: ${TWITCH_OAUTH}

# List accounts for joining
join_to:
  - stealth_unit

## Elastic Client settings
# Connection address
address: http://192.168.88.254:9200

# Name of index for creation
index: stealth_unit

# Name of type for creation
type: chat

# Name of pipeline for processing raw message from grabber
pipeline: msg-parser
