## Twitch Client settings
# Account name
account_name: ${TWITCH_ACCOUNT}

# Account oauth token
# https://twitchapps.com/tmi/
account_token: ${TWITCH_OAUTH}

# List accounts for joining
join_to:
  - vanya83

## Elastic Client settings
# Connection address
address: http://192.168.88.254:9200

# Name of index for creation
index: vanya83

# Name of type for creation
type: chat

# Name of pipeline for processing raw message from grabber
pipeline: msg-parser
